// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtNSCJapiyJ6B1nFXHP02-7flVw4NrWc0',
    appId: '1:998395838291:web:ea863bb344a74fe050eba6',
    messagingSenderId: '998395838291',
    projectId: 'test2-42138',
    authDomain: 'test2-42138.firebaseapp.com',
    storageBucket: 'test2-42138.firebasestorage.app',
    measurementId: 'G-ESXDK586JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCntZYnIHq9MalNu8ukWMeCDKjDosYok',
    appId: '1:998395838291:android:518c61e638de461750eba6',
    messagingSenderId: '998395838291',
    projectId: 'test2-42138',
    storageBucket: 'test2-42138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkWApW5N3EqA_-fUWC_-JXb1Z2Gzeivs',
    appId: '1:998395838291:ios:098e66345a6ec49650eba6',
    messagingSenderId: '998395838291',
    projectId: 'test2-42138',
    storageBucket: 'test2-42138.firebasestorage.app',
    iosBundleId: 'com.example.careNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkWApW5N3EqA_-fUWC_-JXb1Z2Gzeivs',
    appId: '1:998395838291:ios:098e66345a6ec49650eba6',
    messagingSenderId: '998395838291',
    projectId: 'test2-42138',
    storageBucket: 'test2-42138.firebasestorage.app',
    iosBundleId: 'com.example.careNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtNSCJapiyJ6B1nFXHP02-7flVw4NrWc0',
    appId: '1:998395838291:web:9b4387f396ecb8ad50eba6',
    messagingSenderId: '998395838291',
    projectId: 'test2-42138',
    authDomain: 'test2-42138.firebaseapp.com',
    storageBucket: 'test2-42138.firebasestorage.app',
    measurementId: 'G-600RQ5FG2P',
  );
}
